name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 23f2002635@ds.study.iitm.ac.in
        run: echo "Hello, Sarwang! This is your GitHub Action step."

      - name: Run tests
        run: echo "Running tests..."
